GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, LOCK TABLES  ON *.* TO 'flink_user'@'%';
CREATE USER 'hd_user' IDENTIFIED BY 'hd_user_password';
GRANT ALL PRIVILEGES ON *.* TO 'hd_user'@'%';
CREATE DATABASE empty_db;