name: hd
version: '3.9'
networks:
  de_network:
    name: de_network
    external: true
x-common: &common
  image: hd:1.0
  tty: true
  privileged: true
  stdin_open: true
  mem_limit: 4g
  cpus: 4
  user: ${USER}
  extra_hosts:
    - "hd1:172.19.0.11"
    - "hd2:172.19.0.12"
    - "hd3:172.19.0.13"
    - "postgres:172.19.0.14"
  volumes:
    - ${HD_CONFIG_PATH}:${BASE_PATH}/${CONFIG_DIR}:rw
    - ${EXERCISE_PACKAGE_PATH}:${BASE_PATH}/exercise:rw
    - ${BASE_PACKAGE_PATH}/${JAVA_PACKAGE_DIR}:${BASE_PATH}/${JAVA_DIR}:rw
    - ${BASE_PACKAGE_PATH}/${HADOOP_PACKAGE_DIR}:${HADOOP_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${SPARK_PACKAGE_DIR}:${SPARK_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${ZOO_PACKAGE_DIR}:${ZOO_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${KAFKA_PACKAGE_DIR}:${KAFKA_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${HBASE_PACKAGE_DIR}:${HBASE_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${HIVE_PACKAGE_DIR}:${HIVE_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${FLINK_PACKAGE_DIR}:${FLINK_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${CH_PACKAGE_DIR}:${CH_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${ES_PACKAGE_DIR}:${ES_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${MONGODB_PACKAGE_DIR}:${MONGODB_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${MONGOSH_PACKAGE_DIR}:${MONGOSH_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${DORIS_PACKAGE_DIR}:${DORIS_HOME}:rw
    - ${BASE_PACKAGE_PATH}/${USQL_PACKAGE_DIR}:${USQL_HOME}:rw
    - ../../bin:${BASE_PATH}/bin:rw
  environment:
    HD_HOME: ${BASE_PATH}
    HD_DATA_HOME: /var/bigdata
    JAVA_HOME: ${BASE_PATH}/${JAVA_DIR}
    HADOOP_HOME: ${HADOOP_HOME}
    SPARK_HOME: ${SPARK_HOME}
    ZOO_HOME: ${ZOO_HOME}
    KAFKA_HOME: ${KAFKA_HOME}
    HBASE_HOME: ${HBASE_HOME}
    HIVE_HOME: ${HIVE_HOME}
    FLINK_HOME: ${FLINK_HOME}
    CH_HOME: ${CH_HOME}
    ES_HOME: ${ES_HOME}
    MONGODB_HOME: ${MONGODB_HOME}
    MONGOSH_HOME: ${MONGOSH_HOME}
    DORIS_HOME: ${DORIS_HOME}
    USQL_HOME: ${USQL_HOME}
  command: bash ${BASE_PATH}/bin/start.sh
services:
#  postgres:
#    image: postgres:9.4
#    container_name: postgres
#    hostname: postgres
#    restart: always
#    networks:
#      de_network:
#        ipv4_address: 172.19.0.14
#    volumes:
#      - ${HD_CONFIG_PATH}/hive/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh:rw
#    environment:
#      POSTGRES_HOST_AUTH_METHOD: md5
#      POSTGRES_DB: postgres
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: 123456
  hd1:
    <<: *common
    container_name: hd1
    hostname: hd1
    networks:
      de_network:
        ipv4_address: 172.19.0.11
  hd2:
    <<: *common
    container_name: hd2
    hostname: hd2
    networks:
      de_network:
        ipv4_address: 172.19.0.12
  hd3:
    <<: *common
    container_name: hd3
    hostname: hd3
    networks:
      de_network:
        ipv4_address: 172.19.0.13