version: '3'
networks:
  bigdata_network_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
          ip_range: 172.18.0.0/24
services:
  postgres:
    image: postgres:9.4
    platform: linux/arm64
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      bigdata_network_bridge:
        ipv4_address: 172.18.0.2
    volumes:
      - ${CONFIG_PATH}/hive/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh:rw
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
  hd1:
    extends:
      file: ../common/docker-compose.yml
      service: common
    container_name: hd1
    hostname: hd1
    networks:
      bigdata_network_bridge:
        ipv4_address: 172.18.0.11
  hd2:
    extends:
      file: ../common/docker-compose.yml
      service: common
    container_name: hd2
    hostname: hd2
    networks:
      bigdata_network_bridge:
        ipv4_address: 172.18.0.12
  hd3:
    extends:
      file: ../common/docker-compose.yml
      service: common
    container_name: hd3
    hostname: hd3
    networks:
      bigdata_network_bridge:
        ipv4_address: 172.18.0.13