version: '3'
networks:
  bigdata_network_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
          ip_range: 172.18.0.0/24
services:
  hd1:
    extends:
      file: ../common/docker-compose.yml
      service: common
    container_name: hd1
    hostname: hd1
    networks:
      bigdata_network_bridge:
        ipv4_address: 172.18.0.11
  hd2:
    extends:
      file: ../common/docker-compose.yml
      service: common
    container_name: hd2
    hostname: hd2
    networks:
      bigdata_network_bridge:
        ipv4_address: 172.18.0.12
  hd3:
    extends:
      file: ../common/docker-compose.yml
      service: common
    container_name: hd3
    hostname: hd3
    networks:
      bigdata_network_bridge:
        ipv4_address: 172.18.0.13