version: '3'
networks:
  de_network:
    name: de_network
    external: true
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    container_name: mysql
    hostname: mysql
    extra_hosts:
      - "hd1:172.19.0.11"
      - "hd2:172.19.0.12"
      - "hd3:172.19.0.13"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: mysql
      TZ: UTC
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./config/my.cnf:/etc/mysql/my.cnf:rw
      - ./init_db/:/docker-entrypoint-initdb.d/:rw
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    networks:
      de_network:
        ipv4_address: 172.19.0.3
