CREATE USER 'de'@'%' IDENTIFIED BY '123456';
CREATE SCHEMA de COLLATE utf8mb4_general_ci;
GRANT ALL ON de.* TO 'mq'@'%';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, LOCK TABLES  ON *.* TO 'de'@'%';