version: '3'
networks:
  hd_network:
    name: hd_bigdata_network_bridge
    external: true
services:
  airflow:
    image: apache/airflow:2.8.2
    platform: linux/arm64
    container_name: airflow
    hostname: airflow
    restart: always
    command: standalone
    networks:
      hd_network:
        ipv4_address: 172.19.0.3
    volumes:
      - ./dags:/opt/airflow/dags:rw