systemLog.destination: file
systemLog.logAppend: true
systemLog.path: /var/bigdata/log/mongodb/shardsvr.log
storage.dbPath: /var/bigdata/data/mongodb/shardsvr
sharding.clusterRole: shardsvr
processManagement.fork: true
replication.replSetName: hd
net.bindIp: 0.0.0.0
net.port: 27018